In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving npr.csv to npr (4).csv
User uploaded file "npr.csv" with length 55511119 bytes


In [201]:
# Preprocessing on npr dataset 
# www.npr.org
import pandas as pd
npr = pd.read_csv('/content/drive/MyDrive/nlp/npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [202]:
# npr = npr['cleanText']/
len(npr)
print(npr.shape)


(11992, 1)


In [203]:

npr['Article'][1]

'  Donald Trump has used Twitter  —   his preferred means of communication  —   to weigh in on a swath of foreign policy issues over the past few weeks. His comments give a glimpse into how his incoming administration will deal with pressing foreign matters  —   but also highlight how reactionary comments on social media can immediately spur international concern and attention. And his staff has indicated that taking to Twitter to air his concerns or, often, grievances, won’t end once he enters the Oval Office. On Wednesday, Trump blasted the U. S.’s abstention from the U. N. Security Council vote on Israeli settlements earlier this month. The tweets came just hours before Secretary of State John Kerry gave a speech defending the decision and calling the continued building of settlements on Palestinian territory in the West Bank a threat to the   solution in the region. Trump’s support for Israel and Prime Minister Benjamin Netanyahu  —   who has had a fraught relationship with Preside

In [204]:
from sklearn.feature_extraction.text import CountVectorizer

In [205]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
# cv = CountVectorizer(max_df=0.95, min_df=2)
dtm = cv.fit_transform(npr['Article'])

cv.inverse_transform(dtm[1])

[array(['washington', 'policy', 'president', 'obama', 'just', 'called',
        'prime', 'administration', 'ineffective', 'foreign', 'including',
        'weeks', 'office', 'decided', 'cnn', 'said', 'times', 'trump',
        'spoke', 'country', 'week', 'campaign', 'support', 'issues',
        'john', 'issue', 'push', 'concern', 'know', 'time', 'things',
        'end', 'wanted', 'recent', 'security', 'taking', 'outgoing',
        'incoming', 'government', 'denied', 'minister', 'children', 'like',
        'tweeted', 'relationship', 'threat', 'past', 'twitter', 'oval',
        'donald', 'used', 'preferred', 'means', 'communication', 'weigh',
        'swath', 'comments', 'glimpse', 'deal', 'pressing', 'matters',
        'highlight', 'reactionary', 'social', 'media', 'immediately',
        'spur', 'international', 'attention', 'staff', 'indicated', 'air',
        'concerns', 'grievances', 'won', 'enters', 'wednesday', 'blasted',
        'abstention', 'council', 'vote', 'israeli', 'settlemen

In [206]:
dtm[0].shape

(1, 54777)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [207]:
#from sklearn.decomposition import LatentDirichletAllocation
#LDA = LatentDirichletAllocation(n_components=7,random_state=42)
from sklearn.decomposition import NMF
LDA = NMF(n_components=7,random_state=42)
LDA.fit(dtm)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


NMF(n_components=7, random_state=42)

# Three Steps Away...
### Grab the vocab.
### Grab the topic
### and finally grab the highest prob. word per topic



In [208]:
len(cv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [209]:
type(cv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


list

In [210]:
cv.get_feature_names()[5510]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'beret'

In [211]:
import random

In [212]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    # random_word_id = random.randint(0,17408)
    print(cv.get_feature_names()[random_word_id])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


labs
adnan
sized
extend
alleyway
ahmadinejad
davao
advantages
block
dev


### Showing Top Words Per Topic

In [213]:
len(LDA.components_)

7

In [214]:
LDA.components_.shape

(7, 54777)

In [217]:
comp = LDA.components_
comp

array([[2.55233049e-02, 0.00000000e+00, 4.90968123e-04, ...,
        1.16841424e-03, 1.18169925e-03, 2.91895163e-03],
       [7.36991412e-03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.52098632e-01, 0.00000000e+00, ...,
        1.73051772e-03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 7.52276930e-01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.68552180e-02, 8.03450574e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.74473435e-04, 0.00000000e+00],
       [0.00000000e+00, 1.60926042e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [218]:
for i, topic in enumerate(comp):
    print("Topic {}: {}".format(i + 1, ",".join([str(x) for x in idx_to_word[topic.argsort()[-10:]]])))

IndexError: ignored

In [219]:
len(LDA.components_[0])

54777

In [220]:
single_topic = LDA.components_[0]

In [221]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([17319, 18349, 40552, ..., 26752, 36283, 28659])

In [222]:
#lets understand the argsort in simple example
import numpy as np
arr = np.array([10,200,1])
arr.argsort()


array([2, 0, 1])

In [168]:
# Word least representative of this topic
single_topic[18302]

0.13804750358531165

In [169]:
# Word most representative of this topic
single_topic[42997]

0.0

In [170]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([15008, 53211, 49459, 21073, 39848, 27439, 49183, 26752, 36283,
       28659])

In [171]:
top_word_indices = single_topic.argsort()[-10:]

In [172]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


don
way
time
going
really
know
think
just
people
like


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [173]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['new', 'lot', 'make', 'things', 've', 'don', 'way', 'time', 'going', 'really', 'know', 'think', 'just', 'people', 'like']


THE TOP 15 WORDS FOR TOPIC #1
['presidential', 'republicans', 'comey', 'administration', 'obama', 'new', 'election', 'republican', 'white', 'donald', 'house', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['government', 'say', 'city', 'day', 'university', 'year', 'water', 'food', 'time', 'just', 'new', 'years', 'like', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['according', 'reports', 'news', 'department', 'new', 'law', 'time', 'government', 'house', 'npr', 'court', 'told', 'president', 'police', 'said']


THE TOP 15 WORDS FOR TOPIC #4
['country', 'election', 'new', 'states', 'vote', 'party', 'obama', 'democratic', 'voters', 'percent', 'campaign', 'hillary', 'state', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['new', 'percent', 'year', 'parents', 'private', 'kids', 'children', 'student', 'program', 'public', 'educati

### Attaching Discovered Topic Labels to Original Articles

In [174]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [175]:
dtm.shape

(11992, 54777)

In [108]:
len(npr)

98884

In [176]:
topic_results = LDA.transform(dtm)

In [177]:
topic_results.shape

(11992, 7)

In [182]:
topic_results[0]

array([0.05459945, 0.88996904, 0.00661222, 0.24766001, 0.18977488,
       0.01347329, 0.        ])

In [179]:
topic_results[0].round(2)

array([0.05, 0.89, 0.01, 0.25, 0.19, 0.01, 0.  ])

In [ ]:
cv.inverse_transform(topic_results)

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [184]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [185]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 2])

In [186]:
npr['Topic'] = topic_results.argmax(axis=1)

In [187]:
npr.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      3
4   From photography, illustration and video, to d...      5
5   I did not want to join yoga class. I hated tho...      0
6   With a   who has publicly supported the debunk...      6
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      2
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      0
11  For years now, some of the best, wildest, most...      0
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      0
14  Being overweight can raise your blood pressure...      2
15  Who’s the YouTube star of 2016? Adele singing ...      3
16  Here’s a quick roundup of some of the   you ma...      3
17  Ben Johnston doesn’t follow the rules of music...      2
18  David Bowie, Prince and George Michael are all...      0
19  In November, the typically straitlaced Office ...      1